spring:
    application:
        name: expense-service
    data:
        mongodb:
            host: 127.0.0.1
            port: 27017
            database: expense_service
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: 9010

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/